# Generated by Django 3.2.12 on 2022-05-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_accounts', '0003_auto_20220525_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileproxy',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'B - User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name': 'User', 'verbose_name_plural': 'A - Users'},
        ),
    ]
