# Generated by Django 3.2.9 on 2021-11-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bb_data', '0023_alter_colocationclientowner_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='colocationOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_signature', models.BooleanField(default=False)),
                ('nda_signature', models.BooleanField(default=False)),
                ('usd_payout_info', models.BooleanField(default=False)),
                ('crypto_payout_info', models.BooleanField(default=False)),
                ('first_unit_ordered', models.BooleanField(default=False)),
                ('insurance_info_received', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_data.colocationclient')),
            ],
            options={
                'verbose_name': 'Colocation Onboarding',
            },
        ),
    ]
