# Generated by Django 3.2.12 on 2022-05-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bb_data', '0059_auto_20220511_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHistoryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bb_data.billinghistory',),
        ),
    ]
