# Generated by Django 3.2.12 on 2022-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinghistoryproxy',
            options={'verbose_name': 'Billing History', 'verbose_name_plural': 'A - Billing History'},
        ),
    ]
