# Generated by Django 3.2.12 on 2022-05-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_public', '0003_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
