# Generated by Django 3.2.12 on 2022-05-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_public', '0005_contactus_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'B - Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='emailupdatelist',
            options={'verbose_name': 'Email Update List', 'verbose_name_plural': 'A - Email List'},
        ),
    ]
