# Generated by Django 3.2.3 on 2021-06-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColocationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='FiatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField()),
                ('currency', models.CharField(choices=[('$', 'United States Dollar')], max_length=1)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bb_data.colocationclient')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField()),
                ('currency', models.CharField(choices=[('eth', 'ethereum')], max_length=3)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bb_data.colocationclient')),
            ],
        ),
    ]
