# Generated by Django 3.2.3 on 2021-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0002_auto_20210630_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationclient',
            name='vast_api_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
