# Generated by Django 3.2.3 on 2021-06-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0003_colocationclient_vast_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationclient',
            name='eth_deposit_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
