# Generated by Django 3.2.3 on 2021-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0004_colocationclient_eth_deposit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosnapshot',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
    ]
