# Generated by Django 3.2.3 on 2021-06-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0006_auto_20210630_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosnapshot',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=32, max_digits=32, null=True),
        ),
    ]
