# Generated by Django 3.2.3 on 2021-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0007_alter_cryptosnapshot_dollar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatsnapshot',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
    ]
