# Generated by Django 3.2.3 on 2021-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0008_alter_fiatsnapshot_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptosnapshot',
            name='balance',
            field=models.DecimalField(decimal_places=32, max_digits=64),
        ),
        migrations.AlterField(
            model_name='cryptosnapshot',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
    ]
