# Generated by Django 3.2.3 on 2021-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0010_auto_20210710_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clients',
            field=models.ManyToManyField(related_name='clients_owned', through='bb_data.ColocationClientOwner', to='bb_data.ColocationClient'),
        ),
    ]
