# Generated by Django 3.2.3 on 2021-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0011_userprofile_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptosnapshot',
            name='start_period',
            field=models.BooleanField(default=False),
        ),
    ]
