# Generated by Django 3.2.3 on 2021-07-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0012_cryptosnapshot_start_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatsnapshot',
            name='start_period',
            field=models.BooleanField(default=False),
        ),
    ]
