# Generated by Django 3.2.3 on 2021-07-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0013_fiatsnapshot_start_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('currency', models.CharField(choices=[('$', 'United States Dollar')], max_length=1)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bb_data.colocationclient')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=32, max_digits=64)),
                ('currency', models.CharField(choices=[('eth', 'ethereum')], max_length=3)),
                ('dollar_price', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bb_data.colocationclient')),
            ],
        ),
    ]
