# Generated by Django 3.2.3 on 2021-07-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0014_cryptopayout_fiatpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colocationclient',
            options={'verbose_name_plural': 'Colocation Clients'},
        ),
        migrations.AlterModelOptions(
            name='colocationclientowner',
            options={'verbose_name_plural': 'Colocation Client Owners'},
        ),
        migrations.AlterModelOptions(
            name='cryptosnapshot',
            options={'verbose_name_plural': 'Crypto Snapshot'},
        ),
        migrations.RemoveField(
            model_name='colocationclientowner',
            name='owner',
        ),
    ]
