# Generated by Django 3.2.3 on 2021-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0015_auto_20210720_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptopayout',
            options={'verbose_name_plural': 'Crypto Payouts'},
        ),
        migrations.AlterModelOptions(
            name='fiatpayout',
            options={'verbose_name_plural': 'Fiat Payouts'},
        ),
        migrations.AlterModelOptions(
            name='fiatsnapshot',
            options={'verbose_name_plural': 'Fiat Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='cryptopayout',
            name='tx_hash',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
