# Generated by Django 3.2.3 on 2021-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0018_alter_cryptopayout_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayout',
            name='tx_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
