# Generated by Django 3.2.3 on 2021-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0020_fiatpayout_tx_vast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayout',
            name='currency',
            field=models.CharField(choices=[('eth', 'Ethereum')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cryptosnapshot',
            name='currency',
            field=models.CharField(choices=[('eth', 'Ethereum')], max_length=3),
        ),
    ]
