# Generated by Django 3.2.3 on 2021-09-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0021_auto_20210802_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brick_access',
            field=models.BooleanField(default=False),
        ),
    ]
