# Generated by Django 3.2.9 on 2021-11-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0023_alter_colocationclientowner_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationclient',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
