# Generated by Django 3.2.9 on 2021-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0024_colocationclient_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_beta',
            field=models.BooleanField(default=True),
        ),
    ]
