# Generated by Django 3.2.9 on 2021-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0023_equipmentowner'),
        ('bb_data', '0027_colocationclient_term_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationclient',
            name='equipment',
            field=models.ManyToManyField(related_name='owned_equipment', through='bb_vm.EquipmentOwner', to='bb_vm.HostFoundation'),
        ),
    ]
