# Generated by Django 3.2.9 on 2021-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0028_colocationclient_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationclient',
            name='stripe_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_colo',
            field=models.BooleanField(default=False),
        ),
    ]
