# Generated by Django 3.2.9 on 2021-12-10 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bb_data', '0031_auto_20211209_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_data.paymentmethod')),
            ],
            options={
                'verbose_name': 'Users Payment Methods',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_methods',
        ),
        migrations.DeleteModel(
            name='SavedPaymentMethod',
        ),
        migrations.AddField(
            model_name='paymentmethodowner',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_data.userprofile'),
        ),
        migrations.AddField(
            model_name='paymentmethodowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pay_methods',
            field=models.ManyToManyField(related_name='payment_methods_saved', through='bb_data.PaymentMethodOwner', to='bb_data.PaymentMethod'),
        ),
    ]
