# Generated by Django 3.2.9 on 2021-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0032_auto_20211209_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
