# Generated by Django 3.2.10 on 2022-01-26 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bb_data', '0033_auto_20211210_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle_start', models.DateField(auto_now_add=True)),
                ('billing_cycle_end', models.DateField(null=True)),
                ('minutes_3070', models.IntegerField(default=0)),
                ('minutes_3090', models.IntegerField(default=0)),
                ('rate_3070', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('rate_3090', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('balance_paid', models.BooleanField(default=False)),
                ('stripe_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resource Time Tracking',
            },
        ),
    ]
