# Generated by Django 3.2.12 on 2022-02-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0036_billinghistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinghistory',
            options={'verbose_name_plural': 'Billing History'},
        ),
    ]
