# Generated by Django 3.2.12 on 2022-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0037_alter_billinghistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='invoice_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
