# Generated by Django 3.2.12 on 2022-02-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0040_auto_20220207_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='amount_alt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bb_data.resourcetimetracking'),
        ),
    ]
