# Generated by Django 3.2.12 on 2022-02-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0041_auto_20220207_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='amount_alt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
