# Generated by Django 3.2.12 on 2022-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0042_alter_billinghistory_amount_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
    ]
