# Generated by Django 3.2.12 on 2022-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0043_alter_userprofile_is_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetimetracking',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
