# Generated by Django 3.2.12 on 2022-02-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0044_resourcetimetracking_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetimetracking',
            name='rate_3070',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='resourcetimetracking',
            name='rate_3090',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
        ),
        migrations.AlterField(
            model_name='resourcetimetracking',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
