# Generated by Django 3.2.12 on 2022-02-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0045_auto_20220211_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetimetracking',
            name='threshold',
        ),
    ]
