# Generated by Django 3.2.12 on 2022-02-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0046_remove_resourcetimetracking_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
