# Generated by Django 3.2.12 on 2022-02-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0048_sshkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='user',
        ),
        migrations.CreateModel(
            name='SSHKeyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='bb_data.sshkey')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bb_data.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keys',
            field=models.ManyToManyField(related_name='keys_owned', through='bb_data.SSHKeyOwner', to='bb_data.SSHKey'),
        ),
    ]
