# Generated by Django 3.2.12 on 2022-02-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0049_auto_20220219_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
