# Generated by Django 3.2.12 on 2022-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0050_sshkey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='pub_key',
            field=models.TextField(max_length=5000, unique=True),
        ),
    ]
