# Generated by Django 3.2.12 on 2022-03-03 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bb_data', '0052_auto_20220303_1640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
    ]
