# Generated by Django 3.2.12 on 2022-03-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0053_alter_paymentmethod_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
    ]
