# Generated by Django 3.2.12 on 2022-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0054_alter_paymentmethod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
