# Generated by Django 3.2.12 on 2022-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0056_customscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
