# Generated by Django 3.2.12 on 2022-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0057_userprofile_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
