# Generated by Django 3.2.12 on 2022-05-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0058_billinghistory_destroy_vms_countdown_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinghistory',
            name='destroy_vms_countdown_started',
        ),
        migrations.AddField(
            model_name='resourcetimetracking',
            name='destroy_vms_countdown_started',
            field=models.BooleanField(default=False),
        ),
    ]
