# Generated by Django 3.2.3 on 2021-08-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bb_data', '0021_auto_20210802_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortTunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualBrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_uuid', models.CharField(max_length=36, null=True)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualBrickOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb_data.userprofile')),
                ('virt_brick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb_vm.virtualbrick')),
            ],
        ),
        migrations.AddField(
            model_name='virtualbrick',
            name='owners',
            field=models.ManyToManyField(related_name='brick_owner', through='bb_vm.VirtualBrickOwner', to='bb_data.UserProfile'),
        ),
        migrations.AddField(
            model_name='virtualbrick',
            name='ssh_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.porttunnel'),
        ),
        migrations.CreateModel(
            name='HostBrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_username', models.CharField(max_length=64)),
                ('ssh_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb_vm.porttunnel')),
            ],
        ),
    ]
