# Generated by Django 3.2.3 on 2021-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbrick',
            name='name',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
