# Generated by Django 3.2.3 on 2021-08-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0002_virtualbrick_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostBrick',
            new_name='HostFoundation',
        ),
    ]
