# Generated by Django 3.2.3 on 2021-08-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0003_rename_hostbrick_hostfoundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=36)),
                ('pcie', models.CharField(max_length=64)),
                ('device', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb_vm.hostfoundation')),
            ],
        ),
        migrations.CreateModel(
            name='RentedGPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.gpu')),
                ('virt_brick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb_vm.virtualbrick')),
            ],
        ),
        migrations.AddField(
            model_name='virtualbrick',
            name='assigned_gpus',
            field=models.ManyToManyField(related_name='assigned_gpus', through='bb_vm.RentedGPU', to='bb_vm.GPU'),
        ),
    ]
