# Generated by Django 3.2.3 on 2021-08-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0004_auto_20210812_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='xml',
            field=models.TextField(null=True),
        ),
    ]
