# Generated by Django 3.2.3 on 2021-08-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0005_gpu_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedgpu',
            name='virt_brick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bb_vm.virtualbrick'),
        ),
    ]
