# Generated by Django 3.2.3 on 2021-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0006_alter_rentedgpu_virt_brick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostfoundation',
            options={'verbose_name_plural': 'Host Foundations/Servers'},
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='connected_status',
            field=models.BooleanField(default=False),
        ),
    ]
