# Generated by Django 3.2.3 on 2021-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0007_auto_20210915_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name_plural': 'GPUs'},
        ),
        migrations.AlterModelOptions(
            name='rentedgpu',
            options={'verbose_name_plural': 'Rented GPUs'},
        ),
        migrations.AlterModelOptions(
            name='virtualbrick',
            options={'verbose_name_plural': 'Virtual Bricks/Machines'},
        ),
        migrations.AlterModelOptions(
            name='virtualbrickowner',
            options={'verbose_name_plural': 'VM Owners'},
        ),
        migrations.AddField(
            model_name='gpu',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
