# Generated by Django 3.2.3 on 2021-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0008_auto_20210915_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbrick',
            name='img_cloned',
            field=models.BooleanField(default=False),
        ),
    ]
