# Generated by Django 3.2.3 on 2021-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0009_virtualbrick_img_cloned'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbrick',
            name='is_rebooting',
            field=models.BooleanField(default=False),
        ),
    ]
