# Generated by Django 3.2.7 on 2021-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0010_virtualbrick_is_rebooting'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG'), (0, 'NOTSET')])),
                ('virt_brick', models.CharField(max_length=36)),
                ('message', models.TextField()),
            ],
        ),
    ]
