# Generated by Django 3.2.7 on 2021-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0011_vmlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmlog',
            name='level',
            field=models.IntegerField(choices=[(None, 'NOTSET'), (50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG'), (0, 'NOTSET')]),
        ),
    ]
