# Generated by Django 3.2.7 on 2021-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0013_alter_vmlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostfoundation',
            name='serial_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
