# Generated by Django 3.2.7 on 2021-10-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0014_hostfoundation_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualbrick',
            name='domain_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
