# Generated by Django 3.2.7 on 2021-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0015_alter_virtualbrick_domain_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostfoundation',
            name='gpus_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
