# Generated by Django 3.2.7 on 2021-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0016_auto_20211026_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='porttunnel',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
