# Generated by Django 3.2.7 on 2021-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0017_porttunnel_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmlog',
            name='command',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vmlog',
            name='command_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vmlog',
            name='host',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vmlog',
            name='virt_brick',
            field=models.CharField(max_length=32),
        ),
    ]
