# Generated by Django 3.2.7 on 2021-10-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0018_auto_20211028_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbrick',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.hostfoundation'),
        ),
    ]
