# Generated by Django 3.2.7 on 2021-11-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0019_virtualbrick_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostfoundation',
            name='sshtunnel_public_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hostfoundation',
            name='ssh_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.porttunnel'),
        ),
        migrations.AlterField(
            model_name='hostfoundation',
            name='ssh_username',
            field=models.CharField(default='bb_root', max_length=64),
        ),
    ]
