# Generated by Django 3.2.7 on 2021-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0020_auto_20211102_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfoundation',
            name='serial_number',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
