# Generated by Django 3.2.10 on 2021-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0023_equipmentowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentowner',
            name='date_ordered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
