# Generated by Django 3.2.10 on 2022-01-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0024_equipmentowner_date_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostfoundation',
            options={'verbose_name_plural': 'Hosts'},
        ),
        migrations.RemoveField(
            model_name='hostfoundation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hostfoundation',
            name='connected_status',
        ),
        migrations.RemoveField(
            model_name='hostfoundation',
            name='gpus_online',
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='vpn_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
