# Generated by Django 3.2.10 on 2022-01-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0033_auto_20211210_0924'),
        ('bb_vm', '0025_auto_20220110_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBrickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_destroyed', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb_data.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Virtual Brick History',
            },
        ),
    ]
