# Generated by Django 3.2.10 on 2022-01-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0033_auto_20211210_0924'),
        ('bb_vm', '0026_virtualbrickhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualbrickhistory',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_data.userprofile'),
        ),
    ]
