# Generated by Django 3.2.10 on 2022-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0028_virtualbrick_sshtunnel_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='bg_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpu',
            name='bg_running',
            field=models.BooleanField(default=False),
        ),
    ]
