# Generated by Django 3.2.12 on 2022-03-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0031_virtualbrick_is_booting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
                ('checksum_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
