# Generated by Django 3.2.12 on 2022-03-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0032_cloudimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudimage',
            options={'verbose_name_plural': 'Cloud Images'},
        ),
    ]
