# Generated by Django 3.2.12 on 2022-03-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_data', '0056_customscript'),
        ('bb_vm', '0033_alter_cloudimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbrick',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bb_data.customscript'),
        ),
    ]
