# Generated by Django 3.2.12 on 2022-05-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0035_backgroundtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostfoundation',
            options={'verbose_name_plural': 'A - Hosts'},
        ),
    ]
