# Generated by Django 3.2.12 on 2022-05-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0036_alter_hostfoundation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name_plural': 'B - GPUs'},
        ),
    ]
