# Generated by Django 3.2.12 on 2022-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0037_alter_gpu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualbrick',
            options={'verbose_name_plural': 'C - Virtual Machines (Bricks)'},
        ),
        migrations.AddField(
            model_name='virtualbrick',
            name='gpu_count',
            field=models.IntegerField(default=4),
        ),
    ]
