# Generated by Django 3.2.12 on 2022-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0038_auto_20220527_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualbrick',
            old_name='gpu_count',
            new_name='cpu_count',
        ),
    ]
