# Generated by Django 3.2.12 on 2022-05-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0040_virtualbrick_memory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.virtualbrick'),
        ),
    ]
