# Generated by Django 3.2.12 on 2022-05-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0042_auto_20220527_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedgpu',
            name='gpu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='bb_vm.gpu'),
        ),
    ]
