# Generated by Django 3.2.12 on 2022-05-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0043_alter_rentedgpu_gpu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundtask',
            options={'verbose_name_plural': 'F - Background Tasks'},
        ),
        migrations.AlterModelOptions(
            name='cloudimage',
            options={'verbose_name_plural': 'E - Cloud Images'},
        ),
        migrations.AlterModelOptions(
            name='equipmentowner',
            options={'verbose_name_plural': 'K - Equipment Owners'},
        ),
        migrations.AlterModelOptions(
            name='porttunnel',
            options={'verbose_name_plural': 'G - Tunnel Ports'},
        ),
        migrations.AlterModelOptions(
            name='virtualbrickhistory',
            options={'verbose_name_plural': 'H - VM History'},
        ),
        migrations.AlterModelOptions(
            name='virtualbrickowner',
            options={'verbose_name_plural': 'J - VM Owners'},
        ),
        migrations.AlterModelOptions(
            name='vmlog',
            options={'verbose_name_plural': 'I - VM Logs'},
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='cpu_cores',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='hostfoundation',
            name='memory',
            field=models.IntegerField(default=12),
        ),
    ]
