# Generated by Django 3.2.12 on 2022-10-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_vm', '0044_auto_20220531_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb_vm.virtualbrick'),
        ),
    ]
