name: Push Update

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Puller Notification
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: "https://brickbox.io/puller/cd/"
        webhook_secret: "Y0uR5ecr3t"
