name: Push Update

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:

  merge:
    runs-on: ubuntu-latest
    name: Issue Pull Request
    steps:
    - uses: actions/checkout@master

    - name: Puller Notification
      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: "https://brickbox.io/puller/cd/"
        webhook_secret: "Y0uR5ecr3t"
