name: Django CI

on:
  push:
    branches:
      - "**"
      - "master"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 0 | Set Environment Variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "SOCIAL_AUTH_GOOGLE_client_id=${{ secrets.SOCIAL_AUTH_GOOGLE_client_id }}" >> $GITHUB_ENV
          echo "SOCIAL_AUTH_GOOGLE_secret=${{ secrets.SOCIAL_AUTH_GOOGLE_secret }}" >> $GITHUB_ENV
          echo "DEBUG_DB_PASSWORD=${{ secrets.DEBUG_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TEST_DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "STRIPE_CLIENT_ID_TEST=${{ secrets.STRIPE_CLIENT_ID_TEST }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY_TEST=${{ secrets.STRIPE_SECRET_KEY_TEST }}" >> $GITHUB_ENV
          echo "STRIPE_PUBLISHABLE_KEY_TEST=${{ secrets.STRIPE_PUBLISHABLE_KEY_TEST }}" >> $GITHUB_ENV
          echo "STRIPE_CLIENT_ID=${{ secrets.STRIPE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> $GITHUB_ENV
          echo "DO_SPACES_KEY=${{ secrets.DO_SPACES_KEY }}" >> $GITHUB_ENV

      - name: Step 1 | Add IP address to trusted source (managed database)
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "add"
          database_id: 3ece3463-8ce9-4bb2-9362-f6b3fd8e4c42
          digitalocean_token: aad056c20d6d9da0beadbf3028abc712fda675cadbe1b651e1b155736de45bd7

      # Step 2, do whatever you need to do with you database
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 manage.py test --noinput --keepdb

      # - name: Verify Deployment Settings
      #   run: |
      #     python3 manage.py check --deploy --fail-level=WARNING

      # Step 3, remove the IP address
      - name: Remove IP address to trusted source (managed database)
        if: always()
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "remove"
          database_id: 3ece3463-8ce9-4bb2-9362-f6b3fd8e4c42
          digitalocean_token: aad056c20d6d9da0beadbf3028abc712fda675cadbe1b651e1b155736de45bd7
