name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
     - master

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.0.1', '3.1.4', '3.2.5', '3.3.5', '3.4.10', '3.5.9', '3.6.7', '3.7.5', '3.8.1', '3.9.0', '3.10.0' ]

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test --noinput
