name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest



    #NOTE: Could not refrence the job name when using matrix.
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: [3.6]
        #python-version: [3.7, 3.8, 3.9]

    steps:
      # - name: Verify MySQL connection from host
      #  run: |
      #    sudo apt-get install -y mysql-client
      #    mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -urec -ppassword -e "SHOW DATABASES"

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}



      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test --noinput
