name: Django CI

on:
  push:
    branches:
      - "**"
      - "master"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [ '3.8.10', '3.9.0', '3.10.0' ]

    steps:
      # Step 1, add the IP address
      - name: Add IP address to trusted source (managed database)
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "add"
          database_id: 3ece3463-8ce9-4bb2-9362-f6b3fd8e4c42
          digitalocean_token: aad056c20d6d9da0beadbf3028abc712fda675cadbe1b651e1b155736de45bd7

      # Step 2, do whatever you need to do with you database
      - uses: actions/checkout@v3

      # - name: Set up Python ${{ matrix.python-version }}
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0
          # python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python3 manage.py test --noinput --keepdb
          django-admin check --deploy

      # Step 3, remove the IP address
      - name: Remove IP address to trusted source (managed database)
        if: always()
        uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: "remove"
          database_id: 3ece3463-8ce9-4bb2-9362-f6b3fd8e4c42
          digitalocean_token: aad056c20d6d9da0beadbf3028abc712fda675cadbe1b651e1b155736de45bd7
