name: Django Security Check

on:
  push:
    branches:
      - "**"
      - "master"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FAIL_LEVEL: WARNING
  ENV_TYPE: venv
  DEP_PATH: requirements.txt
  APP_PATH:
  # EXTRA_ARGS: "--settings=app.settings.production"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Scan Django settings for security issues
        id: check
        uses: victoriadrake/django-security-check@master
