name: HTML5 Validator

on:
  push:
    branches:
      - "**"
      - "master"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v2

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.0
        with:
          root: bb_public/
          blacklist: invalid
