name: Lighthouse CI
on:
  push:
    branches:
      - "**"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        env:
          DOMAIN: dev
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Select branch name
        uses: actions/hello-world-javascript-action@v1.1
        if: ${{ steps.extract_branch.outputs.branch != 'master' }}
        env:
          DOMAIN: ${{ steps.extract_branch.outputs.branch }}

      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://${{ env.DOMAIN }}.brickbox.io
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: .github/lighthouserc.js
