name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://dev.brickbox.io
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: .github/lighthouserc.js
