name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest

    env:
      DOMAIN: "dev"

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Select branch name
      - uses: actions/hello-world-javascript-action@v1.1
        if: ${{ ${{ steps.extract_branch.outputs.branch }} != "master" }}
        env:
          DOMAIN: ${{ steps.extract_branch.outputs.branch }}

      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://${{ steps.extract_branch.outputs.branch }}.brickbox.io
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: .github/lighthouserc.js
