on: push
name: Create Slate Documentation on Push
jobs:
  slate-documentation:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build documentation
      uses: docker://decathlon/slate-builder-action:2.0.0
      env:
        DOC_BASE_FOLDER = "./bb_api/templates/api_docs_source/"
        ZIP_BUILD = "false"
